repos:
- repo: https://github.com/nicklockwood/SwiftFormat
  rev: 0.52.8
  hooks:
  - id: swiftformat
    args: [--config, .swiftformat, --quiet]
- repo: https://github.com/realm/SwiftLint
  rev: 0.59.1
  hooks:
    - id: swiftlint
      args: [--config, .swiftlint.yml, --strict, --force-exclude]
